### ISSUE TITLE
lazy-load database '/usr/local /lib/R/site-library/stringr/R/stringr.rdb' is corrupt

### ISSUE THREAD

**Issue by cpanse** [protViz/rawDiag#16]
Error in unlist(str_split(x, "\n"), recursive = FALSE, use.names = FALSE): lazy-load database '/usr/local /lib/R/site-library/stringr/R/stringr.rdb' is corrupt

**Comment by wolski** [comment]
This error is discussed here:
https://stackoverflow.com/questions/39560808/rendering-an-rmd-fails-because-stringr-rdb-is-corrupt

Restarting the R-session will solve the problem.
